# docker compose file for 'auto-message-sender-service'
version: "3.9"

name: auto-message-sender-service

networks:
  auto-message-sender-service-network:
    name: auto-message-sender-service-network
    driver: bridge

volumes:
  postgres-vol:
  redis-vol:

services:
  # api
  api-svc:
    image: api-img
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - "${NETWORK_INTERFACE}:${API_SERVER_PORT}:${API_SERVER_PORT}"
    networks:
      - auto-message-sender-service-network

  scheduler-svc:
    image: scheduler-img
    environment:
      - TZ=${TZ}
    restart: always
    networks:
      - auto-message-sender-service-network

  # db
  postgres-svc:
    image: postgres-img
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    ports:
      - "${NETWORK_INTERFACE}:${POSTGRESQL_PORT}:5432"
    networks:
      - auto-message-sender-service-network

  # redis
  redis-svc:
    image: redis-img
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./redis-vol:/data
    ports:
      - "${NETWORK_INTERFACE}:${REDIS_PORT}:6379"
    networks:
      - auto-message-sender-service-network